export  const commonImg =  {
    purple : require("../image/ball-1.png"),
    pink : require("../image/b2.png"),
    orange : require("../image/b3.png"),
    purplelight : require("../image/lightpurple.png"),
    darkorange : require("../image/ora.png"),
    cartoon : require("../image/first.png"),
    paul : require("../image/paul.png"),
    fire : require("../image/aag.png"),
    expression : require("../image/Expressions.png"),
    wall : require("../image/wall.png"),
    bear : require("../image/bear.png"),
    gas : require("../image/gasoline.png"),
    wallet : require("../image/wallet.png"),
    collection : require("../image/collection.png"),
    nft : require("../image/nft.png"),
    sale : require("../image/sale.png"),
    circle : require("../image/circle.png"),
    sun : require("../image/sun.png"),
    green : require("../image/green.png"),
    sunny : require("../image/sunny.png"),
    blue : require("../image/blue.png"),
} 